# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movies.proto',
  package='movie',
  syntax='proto2',
  serialized_pb=_b('\n\x0cmovies.proto\x12\x05movie\"\xd5\x01\n\x05Movie\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0breleaseDate\x18\x02 \x02(\x01\x12\x10\n\x08overview\x18\x03 \x01(\t\x12)\n\x0c\x66\x65\x61turedCrew\x18\x04 \x03(\x0b\x32\x13.movie.Movie.Person\x1a\x37\n\x06Person\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1f\n\x04role\x18\x02 \x02(\x0e\x32\x11.movie.Movie.Role\"3\n\x04Role\x12\r\n\tCHARACTER\x10\x00\x12\x0e\n\nSCREENPLAY\x10\x01\x12\x0c\n\x08\x44IRECTOR\x10\x02\")\n\tMovieList\x12\x1c\n\x06movies\x18\x01 \x03(\x0b\x32\x0c.movie.Movie')
)



_MOVIE_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='movie.Movie.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHARACTER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCREENPLAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTOR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=186,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_MOVIE_ROLE)


_MOVIE_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='movie.Movie.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='movie.Movie.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='movie.Movie.Person.role', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=184,
)

_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='movie.Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='movie.Movie.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='releaseDate', full_name='movie.Movie.releaseDate', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overview', full_name='movie.Movie.overview', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='featuredCrew', full_name='movie.Movie.featuredCrew', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MOVIE_PERSON, ],
  enum_types=[
    _MOVIE_ROLE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=237,
)


_MOVIELIST = _descriptor.Descriptor(
  name='MovieList',
  full_name='movie.MovieList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='movie.MovieList.movies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=280,
)

_MOVIE_PERSON.fields_by_name['role'].enum_type = _MOVIE_ROLE
_MOVIE_PERSON.containing_type = _MOVIE
_MOVIE.fields_by_name['featuredCrew'].message_type = _MOVIE_PERSON
_MOVIE_ROLE.containing_type = _MOVIE
_MOVIELIST.fields_by_name['movies'].message_type = _MOVIE
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.message_types_by_name['MovieList'] = _MOVIELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(

  Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
    DESCRIPTOR = _MOVIE_PERSON,
    __module__ = 'movies_pb2'
    # @@protoc_insertion_point(class_scope:movie.Movie.Person)
    ))
  ,
  DESCRIPTOR = _MOVIE,
  __module__ = 'movies_pb2'
  # @@protoc_insertion_point(class_scope:movie.Movie)
  ))
_sym_db.RegisterMessage(Movie)
_sym_db.RegisterMessage(Movie.Person)

MovieList = _reflection.GeneratedProtocolMessageType('MovieList', (_message.Message,), dict(
  DESCRIPTOR = _MOVIELIST,
  __module__ = 'movies_pb2'
  # @@protoc_insertion_point(class_scope:movie.MovieList)
  ))
_sym_db.RegisterMessage(MovieList)


# @@protoc_insertion_point(module_scope)
